version: 2
jobs:
  chrome_test:
    docker:
      - image: katalonstudio/katalon
    working_dir: ~/
    steps:
      - checkout
      - run:
          name: TestSuite01 by Chrome
          command: |
            katalonc -browserType="Chrome" -retry=0 -statusDelay=15 \
            -testSuitePath="Test Suites/TestSuite01"
      - store-test_results:
          path: ./report
      - store-artifacts:
          path: ./report

workflows:
  version: 2
  tests:
    jobs:
      - chrome_test
